#include "render/builtin-shaders.h"

const char *const shaderVertexSolidSource =
	"#version 300 es\n"
	"uniform mat4 MVP;\n"
	"in vec3 inPos;\n"
	"in vec4 inColor;\n"
	"out vec4 color;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = MVP * vec4(inPos, 1.0);\n"
	"    color = inColor;\n"
	"}\n";
const char *const shaderFragmentSolidSource =
	"#version 300 es\nprecision mediump float;\n"
	"in vec4 color;\n"
	"out vec4 fragColor;\n"
	"void main()\n"
	"{\n"
	"    fragColor = color;\n"
	"}\n";
const char *const shaderFragmentColoredSource =
	"#version 300 es\nprecision mediump float;\n"
	"uniform vec4 color;\n"
	"out vec4 fragColor;\n"
	"void main()\n"
	"{\n"
	"    fragColor = color;\n"
	"}\n";
const char *const shaderVertexTexturedSource =
	"#version 300 es\n"
	"uniform mat4 MVP;\n"
	"in vec3 inPos;\n"
	"in vec2 inTexCoord;\n"
	"out vec2 uv;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = MVP * vec4(inPos, 1.0);\n"
	"    uv = inTexCoord;\n"
	"}\n";
const char *const shaderFragmentTexturedSource =
	"#version 300 es\nprecision mediump float;\n"
	"uniform sampler2D uTexture;\n"
	"in vec2 uv;\n"
	"out vec4 fragColor;\n"
	"void main()\n"
	"{\n"
	"    fragColor = texture(uTexture, uv);\n"
	"}\n";
const char *const shaderFragmentSDFSource =
	"#version 330 core\n"
	"#extension GL_OES_standard_derivatives : enable\n"
	"uniform vec4 color;\n"
	"uniform sampler2D tex;\n"
	"in vec2 uv;\n"
	"out vec4 fragColor;\n"
	"float screenPxRange()\n"
	"{\n"
	"    vec2 unitRange = vec2(6.0) / vec2(textureSize(tex, 0));\n"
	"    vec2 screenTexSize = vec2(1.0) / fwidth(uv);\n"
	"    return max(0.5 * dot(unitRange, screenTexSize), 1.0);\n"
	"}\n"
	"void main()\n"
	"{\n"
	"    vec4 texel = texture(tex, uv);\n"
	"    float pxDist = screenPxRange() * (texel.r - 0.5);\n"
	"    float opacity = clamp(pxDist + 0.5, 0.0, 1.0);\n"
	"    fragColor = vec4(color.rgb, color.a * opacity);\n"
	"}\n";
const char *const shaderFragmentMSDFSource =
	"#version 330 core\n"
	"#extension GL_OES_standard_derivatives : enable\n"
	"uniform vec4 color;\n"
	"uniform sampler2D tex;\n"
	"in vec2 uv;\n"
	"out vec4 fragColor;\n"
	"float median(float r, float g, float b)\n"
	"{\n"
	"    return max(min(r, g), min(max(r, g), b));\n"
	"}\n"
	"float screenPxRange()\n"
	"{\n"
	"    vec2 unitRange = vec2(6.0) / vec2(textureSize(tex, 0));\n"
	"    vec2 screenTexSize = vec2(1.0) / fwidth(uv);\n"
	"    return max(0.5 * dot(unitRange, screenTexSize), 1.0);\n"
	"}\n"
	"void main()\n"
	"{\n"
	"    vec4 texel = texture(tex, uv);\n"
	"    float dist = median(texel.r, texel.g, texel.b);\n"
	"    float pxDist = screenPxRange() * (dist - 0.5);\n"
	"    float opacity = clamp(pxDist + 0.5, 0.0, 1.0);\n"
	"    fragColor = vec4(color.rgb, color.a * opacity);\n"
	"}\n";
const char *const shaderVertexTexturedColoredSource =
	"#version 300 es\n"
	"uniform mat4 MVP;\n"
	"in vec3 inPos;\n"
	"in vec4 inColor;\n"
	"in vec2 inTexCoord;\n"
	"out vec4 color;\n"
	"out vec2 uv;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = MVP * vec4(inPos, 1.0);\n"
	"    uv = inTexCoord;\n"
	"    color = inColor;\n"
	"}\n";
const char *const shaderFragmentMSDFColoredSource =
	"#version 330 core\n"
	"#extension GL_OES_standard_derivatives : enable\n"
	"uniform sampler2D tex;\n"
	"in vec2 uv;\n"
	"in vec4 color;\n"
	"out vec4 fragColor;\n"
	"float median(float r, float g, float b)\n"
	"{\n"
	"    return max(min(r, g), min(max(r, g), b));\n"
	"}\n"
	"float screenPxRange()\n"
	"{\n"
	"    vec2 unitRange = vec2(6.0) / vec2(textureSize(tex, 0));\n"
	"    vec2 screenTexSize = vec2(1.0) / fwidth(uv);\n"
	"    return max(0.5 * dot(unitRange, screenTexSize), 1.0);\n"
	"}\n"
	"void main()\n"
	"{\n"
	"    vec4 texel = texture(tex, uv);\n"
	"    float dist = median(texel.r, texel.g, texel.b);\n"
	"    float pxDist = screenPxRange() * (dist - 0.5);\n"
	"    float opacity = clamp(pxDist + 0.5, 0.0, 1.0);\n"
	"    fragColor = vec4(color.rgb, color.a * opacity);\n"
	"}\n";
const char *const shaderVertexQuadraticSource =
	"#version 300 es\n"
	"uniform mat4 MVP;\n"
	"in vec3 inPos;\n"
	"in vec2 inCurveUV;\n"
	"in vec4 inColor;\n"
	"in float inType;\n"
	"out vec2 uv;\n"
	"out vec4 color;\n"
	"flat out float type;\n"
	"void main()\n"
	"{\n"
	"    gl_Position = MVP * vec4(inPos, 1.0);\n"
	"    uv = inCurveUV;\n"
	"    color = inColor;\n"
	"    type = inType;\n"
	"}\n";
const char *const shaderFragmentQuadraticSource =
	"#version 300 es\nprecision highp float;\n"
	"in vec2 uv;\n"
	"in vec4 color;\n"
	"flat in float type;\n"
	"out vec4 fragColor;\n"
	"void main()\n"
	"{\n"
	"    vec4 base = color;\n"
	"    vec2 ft = uv;\n"
	"    vec2 px = dFdx(ft);\n"
	"    vec2 py = dFdy(ft);\n"
	"    float fx = (2.0 * ft.x) * px.x - px.y;\n"
	"    float fy = (2.0 * ft.x) * py.x - py.y;\n"
	"    float denomSq = fx*fx + fy*fy;\n"
	"    float invDen = inversesqrt(max(denomSq, 1e-12));\n"
	"    float sd = (ft.x * ft.x - ft.y) * invDen;\n"
	"    float orient = -sign(type);\n"
	"    float sdOriented = sd * orient;\n"
	"    float alpha = 0.5 + sdOriented;\n"
	"    float alphaClamped = clamp(alpha, 0.0, 1.0);\n"
	"    fragColor = vec4(base.rgb, base.a * alphaClamped);\n"
	"}\n";
const char *const shaderFragmentQuadraticColoredSource =
	"#version 300 es\nprecision highp float;\n"
	"uniform vec4 color;\n"
	"in vec2 uv;\n"
	"flat in float type;\n"
	"out vec4 fragColor;\n"
	"void main()\n"
	"{\n"
	"    vec4 base = color;\n"
	"    vec2 ft = uv;\n"
	"    vec2 px = dFdx(ft);\n"
	"    vec2 py = dFdy(ft);\n"
	"    float fx = (2.0 * ft.x) * px.x - px.y;\n"
	"    float fy = (2.0 * ft.x) * py.x - py.y;\n"
	"    float denomSq = fx*fx + fy*fy;\n"
	"    float invDen = inversesqrt(max(denomSq, 1e-12));\n"
	"    float sd = (ft.x * ft.x - ft.y) * invDen;\n"
	"    float orient = -sign(type);\n"
	"    float sdOriented = sd * orient;\n"
	"    float alpha = 0.5 + sdOriented;\n"
	"    float alphaClamped = clamp(alpha, 0.0, 1.0);\n"
	"    fragColor = vec4(base.rgb, base.a * alphaClamped);\n"
	"}\n";